site_name: Rete.js
theme: readthedocs
docs_dir: docs
pages:
- 'Getting started': 'index.md'
- 'Editor': 'Editor.md'
- 'Engine': 'Engine.md'
- 'Components': 'Components.md'
- 'Nodes': 'Nodes.md'
- 'Sockets': 'Sockets.md'
- 'Events': 'Events.md'
- 'Plugins': 'Plugins.md'
- 'Controls': 'Controls.md'
- 'Migrate from v0.7.4 to v1.0.0': 'Migrate.md'